[general]
fontname=JetBrainsMono Nerd Font 11
selchars=-A-Za-z0-9,./?%&#:_
scrollback=10000
bgcolor=rgba(26,9,51,0.85)
fgcolor=#f7a8f7
palette_color_0=#241734
palette_color_1=#ff3caf
palette_color_2=#05ffa1
palette_color_3=#fffb96
palette_color_4=#01cdfe
palette_color_5=#b967ff
palette_color_6=#6effff
palette_color_7=#fbe5ff
palette_color_8=#4a3170
palette_color_9=#ff71ce
palette_color_10=#7dffbe
palette_color_11=#ffffb3
palette_color_12=#4ad9ff
palette_color_13=#d294ff
palette_color_14=#aaffff
palette_color_15=#ffffff
color_preset=Custom
cursorblinks=true
cursorunderline=false
audiblebell=false
disablef10=true
disablemenubar=false
hidescrollbar=true
hidemenubar=true
hidepointer=false
hideclosebutton=false
tabpos=top
geometry_columns=100
geometry_rows=28
